version: 2

updates:
- package-ecosystem: github-actions
  directory: "/"
  reviewers: ["@dnlopes"]
  groups:
    patch-minor-updates:
      update-types: [minor, patch]
      applies-to: version-updates
      dependency-type: production
      patterns: ["*"]
    patch-minor-security:
      update-types: [minor, patch]
      applies-to: security-updates
      dependency-type: production
      patterns: ["*"]
  schedule:
    interval: daily
    time: "07:00"
    timezone: Etc/UTC
  commit-message:
    prefix: "deps:"
