version: 2
updates:
- package-ecosystem: github-actions
  labels: ["gh-action deps"]
  groups:
    non-breaking-changes-version-updates:
      update-types: [minor, patch]
      applies-to: version-updates
      dependency-type: production
      patterns: ["*"]
    non-breaking-changes-security-updates:
      update-types: [minor, patch]
      applies-to: security-updates
      dependency-type: production
      patterns: ["*"]
  directory: "/"
  schedule:
    interval: daily
    time: "06:30"
    timezone: "Etc/UTC"
  reviewers:
  - dnlopes
  commit-message:
    prefix: deps
