name-template: "Release v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
include-labels:
  - "major"
  - "minor"
  - "patch"
categories:
  - title: "🚀 Features"
    label: "feature"
  - title: "🐛 Bug Fixes"
    label: "fix"
  - title: "🚧 Maintenance"
    label: "chore"
  - title: "🚨 Breaking Changes"
    label: "breaking-change"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels: ["major"]
  minor:
    labels: ["minor"]
  patch:
    labels: ["patch"]
  default: patch
autolabeler:
  - label: "minor"
    title: ["^(feat):.+$"]
  - label: "patch"
    title: ["^(fix|chore):.+$"]
  - label: "feature"
    title: ["^(feat):.+$"]
  - label: "fix"
    title: ["^(fix):.+$"]
  - label: "chore"
    title: ["^(chore):.+$"]
template: |
  ## Changes

  $CHANGES
