name: InstallCommonTools
description: Installs common tooling for OpenTofu workflows

inputs:
  terraformVersion:
    description: Terraform version to install
    required: false
    default: "1.9.2"
  openTofuVersion:
    description: OpenTofu version to install
    required: false
    default: "1.7.3"
  goVersion:
    description: Terraform version to install
    required: false
    default: "1.22"
  pythonVersion:
    description: Python version to install
    required: false
    default: "3.12"

runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6
      with:
        python-version: ${{ inputs.pythonVersion }}

    - name: Install uv
      uses: yezz123/setup-uv@4819cd88f8d0991d99e4d10c85da3e4d22528951 # v4

    - name: Install Poetry
      uses: abatilo/actions-poetry@0dd19c9498c3dc8728967849d0d2eae428a8a3d8 # v4

    - name: Install pre-commit
      shell: bash
      run: pip install pre-commit

    - name: Setup Poetry local environment
      shell: bash
      run: |
        poetry config virtualenvs.create true --local
        poetry config virtualenvs.in-project true --local

    - name: Install OpenTofu
      uses: opentofu/setup-opentofu@000eeb8522f0572907c393e8151076c205fdba1b # v1
      with:
        tofu_version: ${{ inputs.openTofuVersion }}

    - name: Install Terraform
      uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
      with:
        terraform_version: ${{ inputs.terraformVersion }}

    - name: Install TFLint
      uses: terraform-linters/setup-tflint@4cb9feea73331a35b422df102992a03a44a3bb33 # v6

    - name: Install Trivy
      shell: bash
      run: curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.52.2

    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
      with:
        go-version: ${{ inputs.goVersion }}
