name: InstallCommonTools
description: Installs common tooling for OpenTofu workflows

inputs:
  terraformVersion:
    description: Terraform version to install
    required: false
    default: "1.9.2"
  openTofuVersion:
    description: OpenTofu version to install
    required: false
    default: "1.7.3"
  goVersion:
    description: Terraform version to install
    required: false
    default: "1.22"
  pythonVersion:
    description: Python version to install
    required: false
    default: "3.12"

runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
      with:
        python-version: ${{ inputs.pythonVersion }}

    - name: Install uv
      uses: yezz123/setup-uv@4819cd88f8d0991d99e4d10c85da3e4d22528951 # v4

    - name: Install pre-commit
      shell: bash
      run: pip install pre-commit

    - name: Install OpenTofu
      uses: opentofu/setup-opentofu@fc711fa910b93cba0f3fbecaafc9f42fd0c411cb # v2
      with:
        tofu_version: ${{ inputs.openTofuVersion }}

    - name: Install Terraform
      uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4
      with:
        terraform_version: ${{ inputs.terraformVersion }}

    - name: Install TFLint
      uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93 # v6

    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
      with:
        go-version: ${{ inputs.goVersion }}
