name: InstallCommonTools
description: Installs common tooling for OpenTofu workflows

inputs:
  terraformVersion:
    description: Terraform version to install
    required: false
    default: "1.9.2"
  openTofuVersion:
    description: OpenTofu version to install
    required: false
    default: "1.7.3"
  goVersion:
    description: Terraform version to install
    required: false
    default: "1.22"
  pythonVersion:
    description: Python version to install
    required: false
    default: "3.12"

runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
      with:
        python-version: ${{ inputs.pythonVersion }}

    - name: Install uv
      uses: yezz123/setup-uv@4819cd88f8d0991d99e4d10c85da3e4d22528951 # v4

    - name: Install Poetry
      uses: abatilo/actions-poetry@0dd19c9498c3dc8728967849d0d2eae428a8a3d8 # v4

    - name: Install pre-commit
      shell: bash
      run: pip install pre-commit

    - name: Setup Poetry local environment
      shell: bash
      run: |
        poetry config virtualenvs.create true --local
        poetry config virtualenvs.in-project true --local

    - name: Install OpenTofu
      uses: opentofu/setup-opentofu@592200bd4b9bbf4772ace78f887668b1aee8f716 # v1
      with:
        tofu_version: ${{ inputs.openTofuVersion }}

    - name: Install Terraform
      uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
      with:
        terraform_version: ${{ inputs.terraformVersion }}

    - name: Install TFLint
      uses: terraform-linters/setup-tflint@90f302c255ef959cbfb4bd10581afecdb7ece3e6 # v4

    - name: Install Trivy
      shell: bash
      run: curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.52.2

    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
      with:
        go-version: ${{ inputs.goVersion }}
