name: PR checks
on:
  workflow_call:

jobs:
  semantic_pr_title:
    name: Semantic title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: false
          subjectPattern: ^(?![A-Z]).+$ # don't start with an uppercase character.
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
          types: |
            fix
            feat
            chore
            breaking-change

  semantic_pr_labels:
    name: Semantic labels
    needs:
      - semantic_pr_labels
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels@v1
        name: Add conventional release labels

  enforce_label:
    needs:
      - semantic_pr_labels
    name: Enforce labels
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v5
        name: Enforce semantic labels
        with:
          mode: exactly
          count: 1
          labels: "feat, fix, chore, breaking"

      - uses: mheap/github-action-required-labels@v5
        name: Enforce banned labels
        with:
          mode: exactly
          count: 0
          labels: "do-not-merge, WIP, do not merge"
