name: Spacelift stack execution
on:
  workflow_call:
    inputs:
      stack_name:
        required: true
        description: "The Spacelift stack name."
        type: string
      spacelift_api_endpoing:
        required: true
        description: "Name of the Spacelift API endpoint"
        type: string
      action:
        required: true
        description: "The type of action to execute in Spacelift (preview, deploy)"
        type: string
      commit_ref:
        required: true
        description: "The Git reference to checkout."
        type: string
      concurrency_group:
        required: false
        description: "Name of concurrency group to manage concurrent Github action runs"
        type: string
        default: ${{ github.repository }}
    secrets:
      GH_API_TOKEN:
        required: true
      SPACELIFT_API_KEY_ID:
        required: false
      SPACELIFT_API_KEY_SECRET:
        required: false

jobs:
  spacelift:
    name: Spacelift
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ inputs.concurrency_group }}-${{ inputs.stack_name }}
      cancel-in-progress: false
    env:
      SPACELIFT_API_KEY_ID: ${{ secrets.SPACELIFT_API_KEY_ID }}
      SPACELIFT_API_KEY_SECRET: ${{ secrets.SPACELIFT_API_KEY_SECRET }}
      SPACELIFT_API_KEY_ENDPOINT: ${{ inputs.spacelift_api_endpoing }}
      GITHUB_TOKEN: ${{ secrets.GH_API_TOKEN }}

    steps:
      - name: Checkout ${{ inputs.commit_ref }}
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_ref }}

      - name: Install spacectl
        uses: spacelift-io/setup-spacectl@main

      - name: Lock stack
        run: spacectl stack lock --id ${{ inputs.stack_name }}

      - name: Enable stack
        run: spacectl stack enable --id ${{ inputs.stack_name }}

      - name: Update stack commit ref
        run: |
          commitSha=$(git rev-parse HEAD)
          spacectl stack set-current-commit --id ${{ inputs.stack_name }} --sha $commitSha

      - name: Stack ${{ inputs.action }}
        run: spacectl stack ${{ inputs.action }} --id ${{ inputs.stack_name }} --tail

      - name: Disable stack
        if: always()
        run: spacectl stack disable --id ${{ inputs.stack_name }}

      - name: Unlock Stack
        if: always()
        run: spacectl stack unlock --id ${{ inputs.stack_name }}
