name: Terraform
on:
  workflow_call:
    inputs:
      action:
        required: true
        description: "The type of action to execute in Spacelift (preview, deploy)"
        type: string
      concurrency_group:
        required: false
        description: "Name of concurrency group to manage concurrent Github action runs"
        type: string
        default: ${{ github.repository }}
    secrets:
      GH_API_TOKEN:
        required: true
      INFRACOST_API_KEY:
        required: false

jobs:
  terraform-checks:
    if: false
    name: Terraform Validations
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    concurrency:
      group: ${{ inputs.concurrency_group }}-terraform-checks
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - uses: terraform-linters/setup-tflint@v3
        name: Setup TFLint

      - name: Run TFLint
        run: tflint --format compact

  infracost:
    if: ${{ github.event.type }} == "pull_request"
    name: Infracost
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    concurrency:
      group: ${{ inputs.concurrency_group }}-infracost
      cancel-in-progress: true

    steps:
      - name: Setup
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      # Checkout the base branch of the pull request (e.g. main/master).
      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: "${{ github.event.pull_request.base.ref }}"

      # Generate Infracost JSON file as the baseline.
      - name: Generate baseline
        run: infracost breakdown --path=${TF_ROOT} --format=json --out-file=/tmp/infracost-base.json

      # Checkout the current PR branch so we can create a diff.
      - name: Checkout PR branch
        uses: actions/checkout@v4

      # Generate an Infracost diff and save it to a JSON file.
      - name: Generate cost diff
        run: infracost diff --path=${TF_ROOT} --format=json --compare-to=/tmp/infracost-base.json --out-file=/tmp/infracost.json

      - name: PR comment
        run: infracost comment github --path=/tmp/infracost.json --repo=$GITHUB_REPOSITORY --github-token=${{github.token}} --pull-request=${{github.event.pull_request.number}} --behavior=delete-and-new
